pipeline{
    agent any
    tools{ 
    maven 'M2_HOME'
    }
    stages{
        stage ("maven"){
            dir ("/var/lib/jenkins/workspace/geo-solution/geo")
             steps{
               sh 'mvn clean validate compile install test package'
            } 
    }   }
}