pipeline{
    agent any
    tools{ 
    maven 'M2_HOME'
    }
    stages{
        stage ("maven"){
            dir ('geo'){
             steps{
               sh 'mvn clean validate compile install test package'
            } 
            }
      }
      
    }
}